### ISSUE TITLE
Update the last comment instead of adding a new one

### ISSUE THREAD

**Issue by caiolopes** [Madrapps/jacoco-report#11]
Can we get an option to update the last comment instead of creating a new one every time?

Very similar to the approach on https://github.com/EnricoMi/publish-unit-test-result-action where we can set the `comment_mode` to either `update last` or `create new`.

**Comment by georgespalding** [comment]
I checked out the docs for [marocchino/sticky-pull-request-comment@v2](https://github.com/marocchino/sticky-pull-request-comment): And I'd ❤️ if something similar could be implemented for this action.

**Comment by sammcj** [comment]
Really keen to see this merged in!
