### ISSUE TITLE
comment base branch coverage

### ISSUE THREAD

**Issue by abhimaandunzo** [Madrapps/jacoco-report#12]
It would be a very useful information if we are able calculate the base branch coverage or at-least we are able to tell the total coverage difference from the base branch.

**Comment by ptsiogas** [comment]
That would be awesome!

**Comment by thsaravana** [comment]
The action itself doesn't store the coverage info generated anywhere. It simply parses the "jacoco" report that is generated during the build. So all you need to do is to give it the right jacoco report and it will give you the output. So if you could configure your "build.gradle" to store the jacoco report of the base branch somewhere, and then refer that file in the `paths` of the setup, it will now show your the base branch coverage.

**Comment by thsaravana** [comment]
Running the base-branch coverage is not in the scope of jacoco-report. However, we will try to show the diff of the coverage for each files (based on if the changed line is covered or not). I will tackle that as part of this issue https://github.com/Madrapps/jacoco-report/issues/25 . So closing this issue.
