### ISSUE TITLE
Is it possible to also post the summary in the github actions summary

### ISSUE THREAD

**Issue by hellosagar** [Madrapps/jacoco-report#123]
Is there a way to use the output from an action to post it under the GitHub summary instead of the PR comment section, as adding stuff in the comment makes it a bit lengthy?

**Comment by thsaravana** [comment]
We don't currently have that feature. But definitely something that we would like to explore. @instrap I think we can try pushing this in Milestone 1.8. What do you think?

This is also related to https://github.com/Madrapps/jacoco-report/issues/38. So, we will try to tackle this as well, along with it (if possible)

**Comment by instrap** [comment]
This seems simple, so we should do this in `1.7.2` itself. It's not a big change. Tagging this to 1.7.2, unless you have a different opinion @thsaravana 😄

**Comment by thsaravana** [comment]
This is now available in [v1.7.2-alpha](https://github.com/Madrapps/jacoco-report/releases/tag/v1.7.2-alpha). We will release v1.7.2 in the coming weeks.
