### ISSUE TITLE
Get badge for Readme file

### ISSUE THREAD

**Issue by ptsiogas** [Madrapps/jacoco-report#14]
It would be nice if we could get a badge for the default branch Readme file in order to easily display the coverage percentage.

**Comment by thsaravana** [comment]
This is not in the scope of this action. But if someone can find a way to do this, I am all ears :)

**Comment by thsaravana** [comment]
I investigated this a bit and this doesn't seem possible without some server. So for now, I don't think this is not possible within the jacoco-report action. However, jacoco-report exposes the Coverage information as `outputs`. So you can use one of many [Add Badges actions in the marketplace](https://github.com/marketplace?type=actions&query=badges) and use the  `output` from jacoco-report and generate the bage.
