### ISSUE TITLE
Github action fails

### ISSUE THREAD

**Issue by yadvr** [Madrapps/jacoco-report#15]
Hi @thsaravana, I'm trying to use the github action here:
https://github.com/apache/cloudstack/runs/5872989662?check_suite_focus=true

It's failing with:

```
Run Madrapps/jacoco-report@fd4800e8a81e21bdf373438e5918b975df041d15
Event is pull_request
base sha: 6bf8[12](https://github.com/apache/cloudstack/runs/5872989662?check_suite_focus=true#step:6:12)cdc93ebe7ec3b5ef38a315407a58834479
head sha: c9ef34cd49308[13](https://github.com/apache/cloudstack/runs/5872989662?check_suite_focus=true#step:6:13)4b33a510dd87488c8233b36fd
Error: TypeError: Cannot read property '$' of undefined
```

The action is being run against a large Java based project, I'm not sure if the action has a limit on the size of the jococo xml. Any advice how to debug this further?

**Comment by thsaravana** [comment]
Hi @rohityadavcloud, could you try using `uses: madrapps/jacoco-report@main` in your workflow?

**Comment by chen-ni-hotstar** [comment]
Hi @thsaravana , just tried `uses: madrapps/jacoco-report@main` but still got the same issue..
