### ISSUE TITLE
not seeing the comment as a bot

### ISSUE THREAD

**Issue by fincode-mo** [Madrapps/jacoco-report#16]
in the example it shows the coverage comment is added by a bot. But for me it says my name, how do I make so comment is added by an automated bot ?

<img width="1123" alt="Screenshot 2022-04-12 at 16 15 32" src="https://user-images.githubusercontent.com/72980525/162995642-b66ec345-844d-464b-b007-4e49d63cf5cf.png">

**Comment by thsaravana** [comment]
Could you share your github workflow yml file?
Are you using `token: ${{ secrets.GITHUB_TOKEN }}` or your own generated developer token?
