### ISSUE TITLE
Wildcard in report paths?

### ISSUE THREAD

**Issue by vasanthdharmaraj** [Madrapps/jacoco-report#20]
I wanted to check if there is wildcard support when the `paths` is configured. From the sample in https://github.com/thsaravana/jacoco-android-playground/blob/main/.github/workflows/coverage.yml  I see that we can add multiple paths as:

```
        paths: |
          ${{ github.workspace }}/app/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
          ${{ github.workspace }}/math/build/reports/jacoco/debugCoverage/debugCoverage.xml,
          ${{ github.workspace }}/text/build/reports/jacoco/debugCoverage/debugCoverage.xml
```

We have a very large number of modules. Listing all the files would be not be efficient. Can we do something like:
```
        paths: |
          ${{ github.workspace }}/**/build/reports/**/*Coverage.xml

```

**Comment by rfasioli** [comment]
I agree! Like the files parameters in similar project: https://github.com/EnricoMi/publish-unit-test-result-action

In python: https://github.com/EnricoMi/publish-unit-test-result-action/blob/c82c0f5f17f75f6020f53d7bf5524286c3259fdc/python/publish_unit_test_results.py#L49-L59

**Comment by thsaravana** [comment]
Looks possible. Adding this to milestone 1.4

**Comment by mfsiega-airbyte** [comment]
Hi @thsaravana - just wanted to check if there's an idea of when 1.4 is coming, or how much work this would be? Thanks!

**Comment by thsaravana** [comment]
I am planning to tackle this as part of supporting multi module reports.
