### ISSUE TITLE
Coverage diff - source vs target

### ISSUE THREAD

**Issue by tfij** [Madrapps/jacoco-report#25]
How about running coverage on both the source and target branches (not sure how to set up such a GitHub action) and then adding information about the difference (does the coverage increase o decrease) in the PR comment?

**Comment by thsaravana** [comment]
I am working on an initiative as part of v1.6, to show the coverage diff. But this would be based on the the Diff that Github provides. The idea is the get the Lines (line number) that are modified (added, modified, deleted) and then check if the lines are covered or not from jacoco report. The problem with this is Github doesn't give us the exact diff of the lines, but a short range of lines. So I suppose it will be an approximate coverage diff.
