### ISSUE TITLE
Ability to Combine Coverage Reporting for Matrix jobs

### ISSUE THREAD

**Issue by JuriKiin** [Madrapps/jacoco-report#28]
As the title suggests, it's nice to batch the jobs for a multi-module project, however it either a) overwrites the single comment for that module, or b) adds a new comment. For large projects, this essentially is equal to 5+ comments for a single PR.

It'd be nice to allow the action to combine the results of different matrix jobs into a single comment with a table for each module.

(I'm fairly new to GHA so I'm not entirely sure this is possible, but I would think there's a way to make it)

**Comment by thsaravana** [comment]
I believe this will be solved with the Support for Multi-Module planned for v1.5. The idea is to publish a single comment that shows coverage for each modules (below each module, you will see a 'details' tab that you can expand to see the individual file's coverage as well).
