### ISSUE TITLE
Support github action event scheduling or workflow dispatch

### ISSUE THREAD

**Issue by bisrinursa** [Madrapps/jacoco-report#34]
**Overview**
The github action supports push & pull event only. It would be essential to support either event scheduling or workflow dispatch.

**Screenshot**
<img width="581" alt="Screen Shot 2022-12-22 at 17 40 59" src="https://user-images.githubusercontent.com/3761901/209135260-66dc73d7-1fd9-484d-9f3c-89f0e4aed4e6.png">

**Comment by thsaravana** [comment]
It should be straight forward to support this. If so, we can actually support this in v1.6.

**Comment by instrap** [comment]
This is in progress and will be released in `v1.7.2`.
