### ISSUE TITLE
action using deprecate 'set-output' command

### ISSUE THREAD

**Issue by MarcelWildenburg** [Madrapps/jacoco-report#35]
The action **madrapps/jacoco-report@v1.3** is using a deprecated 'set-output' command. 
The log is showing the following warning twice : _Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/_

Can this be changed as mentioned in  https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ ?

**Comment by bisgardo** [comment]
Is this going to be addressed? This will start failing on 31st May 2023 which is not that far from now...

**Comment by zak-flex** [comment]
https://github.com/Madrapps/jacoco-report/pull/29 makes an attempt but it needs some updates.

**Comment by georgespalding** [comment]
I addressed the comments on #29 and opened #35 hoping it might get picked up.

**Comment by zak-flex** [comment]
> I addressed the comments on #29 and opened #35 hoping it might get picked up.

Looks like 35 is a typo and it should be #41

**Comment by osman-swarm** [comment]
I see this was merged yesterday - any ETA on when v1.4 will be release?

**Comment by JoshMcCullough** [comment]
If you're nervous, you can update your action usage:
```
madrapps/jacoco-report@7ce0d588f6d00dd4a7b63a597383332e0c5c72d0
```

**Comment by thsaravana** [comment]
Sorry for the extremely late response. Thanks again for bringing this to attention and your collaboration.
v1.4 was released on May 31. So I am closing this ticket.
