### ISSUE TITLE
Not only support instructions coverage, but also line coverage

### ISSUE THREAD

**Issue by sgc109** [Madrapps/jacoco-report#36]
It seems like jacoco-report using instructions counters in a report Jacoco generated to calculate the entire coverage.

Can't I change this to use line counters?

**Comment by thsaravana** [comment]
Sadly there is no way to configure this right now. But I am thinking of adding an option to configure this. I will add more info here soon.

**Comment by thsaravana** [comment]
I am rethinking again how we can do this effectively. As far as I checked, INSTRUCTIONS seems to be more accurate than LINE counter. We have the LINE counter for File, Module and Project level, but not at Line level. For each Line, we have INSTRUCTION and BRANCH but not Line.
So how do we determine if a Line is covered or not? For now, we depend on INSTRUCTION. But this also is not fully correct. We can have a Line that has a BRANCH but no INSTRUCTION. 

🤔

**Comment by gokhan-oner** [comment]
@thsaravana Jacoco itself reports instruction & branch coverage, so I suggest adding support for branch coverage, rather than line coverage. As you said, if it was accurate, I'd assume Jacoco itself will visualize it anyways!

**Comment by instrap** [comment]
Closing this as we will pursue adding Branch Coverage as part of #60.
