### ISSUE TITLE
How to generate a bot comment

### ISSUE THREAD

**Issue by KelvinMock-Telus** [Madrapps/jacoco-report#37]
It seems like in the guide the output is expected to be displayed as a comment generated by the bot, showing the code coverage result from JaCoCo. I copied the example workflow. But neither a line does the work. 
So how can I have the bot generate such comment? And how can I view the coverage result with GitHub Action after running the workflow?

**Comment by NikhilBhutani** [comment]
Hey @KelvinMock-Telus How did you resolve this issue? I'm facing the same

**Comment by KelvinMock-Telus** [comment]
Good day @NikhilBhutani,
I guess the workflow here will be triggered properly only when a pull request is sent. 
Anyways, this workflow doesn't seem helpful in my project unfortunately. 
Alternatively, to generate a summary of the code coverage %, I used another workflow (called cicirello/jacoco-badge-generator@v2) that instead generates a batch after launching the workflow. It is simple enough to understand!
