### ISSUE TITLE
Show full coverage report on new / modified files

### ISSUE THREAD

**Issue by pavelfomin** [Madrapps/jacoco-report#38]
Thank you for making this action available! One suggestion I have is to include full coverage report for new / modified files.
Typically, to approve a PR I would like to see the full coverage report on new / modified files (w/out checking out the branch and running the build to generate the full code coverage report locally):
<img width="950" alt="image" src="https://user-images.githubusercontent.com/2952816/217859224-d9701880-6e7e-4e0b-9f9e-c7c86d9135a2.png">
Would be nice to have this feature.

**Comment by thsaravana** [comment]
It's not possible to add the full jacoco report to the PR comment. That would be really long. May be, we can expose this report in the Github workflow run.
Let me see if we can do that!

**Comment by MichaelMiles** [comment]
yeah it would be nice to have a full jacoco report shown somewhere, is this feature in progress?

**Comment by instrap** [comment]
I took a look at this, and this doesn't seem to be feasible. The easiest option would be to just add another step in your workflow to upload the Coverage html package. Trying to implement what jacoco does is a huge venture. 
We are working on a couple of things that will enable this partially. #88 #60 #67 . But there is no plans to upload the full html as part of this action. So closing this.
