### ISSUE TITLE
Lack of support for multi module aggregated raports

### ISSUE THREAD

**Issue by dabkowski** [Madrapps/jacoco-report#40]
Multi module aggregated raport is created succesfully but the execution fails on iteration of changed files with `Error: TypeError: Cannot read property 'forEach' of undefined` error. Is this feature supported?

**Comment by Rafaesp** [comment]
Looks like it's not supported, I get this same error: https://github.com/Madrapps/jacoco-report/issues/39

I'm also interested on it 🙏 🙇

**Comment by thsaravana** [comment]
I am on it. This will be released soon in v1.5.
