### ISSUE TITLE
Tech Debt - Migrate from JS to TS

### ISSUE THREAD

**Issue by thsaravana** [Madrapps/jacoco-report#48]
Working with Javascript is a bit tricky and I think Typescript is much safer. Refer to [this](https://github.com/actions/typescript-action) and migrate this repo to Typescript.

**Comment by instrap** [comment]
@thsaravana Once this is done, we can directly merge this to `main` since there is no change to README.md. This will ensure that other contributors can raise PR against the TS version and not the current JS version.
