### ISSUE TITLE
Fails in PR with "TypeError: Cannot read properties of undefined (reading 'split')"

### ISSUE THREAD

**Issue by languitar** [Madrapps/jacoco-report#66]
I have a PR in a project, where the action suddenly fails with the following error message:

> Error: TypeError: Cannot read properties of undefined (reading 'split')

All other PRs work, also with the same version of the action.

In debug mode also no helpful information is printed. I only see the resolved path of the XML file before the action dies.

**Comment by kimakunc** [comment]
Hi, I have the same issue - any version of it that works for you ?

**Comment by joelhullflex** [comment]
I updated the jacoco-report version from 1.6 to 1.6.1.  Fix it.
