### ISSUE TITLE
Coverage is not displayed in PR comment. 

### ISSUE THREAD

**Issue by ihorkucharchuk** [Madrapps/jacoco-report#7]
I'm trying to use jacoco-report@v1.2 with a multi-module project.  Jacoco reports are generated, paths to jacoco.xml files are set, but after successful action run I have nothing in the PR comment. End of the log file in debug mode: 
 overallCoverage: [object Object]
 filesCoverage: {
     "files": [],
     "percentage": 100
 }
My Jenkins env is able to display the same Jacoco reports, so they are ok.

**Comment by thsaravana** [comment]
Let me check and get back.
By the way, is this an android project or a multi module java project ?

**Comment by ihorkucharchuk** [comment]
multi module java

**Comment by ihorkucharchuk** [comment]
The root cause was environmental, wrong configs
