### ISSUE TITLE
Getting error while setting up multi module project

### ISSUE THREAD

**Issue by slice-saransh-gupta** [Madrapps/jacoco-report#72]
Was trying to setup jacoco reports for a android multi module project

```
Rules I have used

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 80
          update-comment: true
          debug-mode: true
          title: Code Coverage
      - name: Get the Coverage info
        run: |
            echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
            echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Fail PR if changed file coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall changed file coverage is less than 80%!')
```

Error I am getting
<img width="1295" alt="Screenshot 2023-10-14 at 7 16 44 PM" src="https://github.com/Madrapps/jacoco-report/assets/137060837/fd958ff6-d904-43dc-8822-24e1ce6cbd84">

**Comment by CalixtoElProgramador** [comment]
I have the same issue

**Comment by zetbrush** [comment]
Hey there, any update on this issue ? @thsaravana

**Comment by CalixtoElProgramador** [comment]
by the way, I managed to solve this by deleting the testing directories that did not contain any test in each of the modules

**Comment by zetbrush** [comment]
@CalixtoElProgramador thx for info, in my case jacoco configs are applied to the modules only - that actually contain test classes, and other modules don't contain test folders as well

**Comment by thsaravana** [comment]
This should no longer happen in 'v1.7.1'. Please report if you still face this issue. Empty coverage reports will now be ignored.

**Comment by instrap** [comment]
Please feel free to reopen this if you still face this issue.
