### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by Pravin3c** [Madrapps/jacoco-report#81]
Description:
While using the madrapps/jacoco-report@v1.6.1 action, we are seeing the below warning in the GitHub workflow - 
**Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: madrapps/jacoco-report@v1.6.1.** For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

![image](https://github.com/Madrapps/jacoco-report/assets/38044360/b850f24e-996e-4e47-bbf1-d61c78a85baf)

Can we try to upgrade the Node.js version in action madrapps/jacoco-report?

**Comment by georgespalding** [comment]
See https://github.com/Madrapps/jacoco-report/pull/78

**Comment by MGaetan89** [comment]
#78 has been merged, and should be released with v1.7.
I guess this issue can be closed.
