### ISSUE TITLE
What do the delta figures mean?

### ISSUE THREAD

**Issue by JoseAlcerreca** [Madrapps/jacoco-report#83]
Thanks for this action, we're trying it out in android/nowinandroid.

![image](https://github.com/Madrapps/jacoco-report/assets/609125/823677e4-bb22-4dd1-b9f3-4b410fff8b13)

What do the the deltas mean? E.g. `-0.13%`? It looks like a comparison with the base branch, which would be nice, but I think that's impossible.  

I've spent 10 minutes trying to fint the answer, so I think the README should explain it.

**Comment by sheepkacper** [comment]
Here is the part of the code that calculates it:
<details>
<img width="729" alt="image" src="https://github.com/Madrapps/jacoco-report/assets/84314861/0daedd49-7ca1-412b-9148-96a1600a8c66">
</details>

and this is the actual method:
<details>

<img width="576" alt="image" src="https://github.com/Madrapps/jacoco-report/assets/84314861/6f6861bc-6d33-4226-a297-04ace5d7157e">
</details>

**Comment by thsaravana** [comment]
Yes, I will add this to the `README.md`

You are right, the `delta` is not calculated based on the base branch (which is sadly not possible). Instead, it does the next closest thing. 

Let's say you add or modify 10 lines of code in a file. If you have also added unit tests, that covers 8 lines out of those 10 lines, i.e, 2 lines are not covered by any tests, then the delta would be `-20%`. So the `delta` essentially gives you visibility on how many newly added/modified lines are not covered by unit tests.

This does have it's own limitations. For instance, the delta can never be positive, i.e, if you raise a PR with more Unit Tests adding coverage to exiting code (non modified one), those won't be considered in calculating the delta, as there is no way to figure that out.
