### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by vincent-fuchs** [Madrapps/jacoco-report#84]
Using v1.6.1, we regularly get this error

    TypeError: Cannot read properties of undefined (reading 'split')

<img width="1088" alt="image" src="https://github.com/Madrapps/jacoco-report/assets/9657583/fd9b08ce-ab1b-458c-9a0b-924bfe01176b">

how do we debug this ? the output is not really helpful at the moment 

thanks

**Comment by thsaravana** [comment]
This is fixed in v1.7.0-alpha. Please reopen this, if this still happens.
