### ISSUE TITLE
Report not adding to the PR console

### ISSUE THREAD

**Issue by Bhuvanaarkala07** [Madrapps/jacoco-report#87]
Hi

We have upgraded to the latest version 1.6.1
But this is not adding the aggregated value to the pr.
it is just saying below even thought there are some coverage changes in the pr.
<img width="947" alt="Screenshot 2024-04-09 at 6 52 30 PM" src="https://github.com/Madrapps/jacoco-report/assets/14951463/c2229989-2f01-4506-b3e0-da018f33e05b">

Using Java17

Any help would be appreciated.

Thanks in advance

**Comment by Bhuvanaarkala07** [comment]
It is showing this, 

Run madrapps/jacoco-report@v1.6.1
Event is pull_request
base sha: aceb8b21d602b8bcf2d5d86700ca8583dab633a0
head sha: a5f79c7[17](https://github.com/forge-tech/fsandroid/actions/runs/8619884373/job/23625538196?pr=615#step:9:18)702d4b7f7b91990bcafa126583bf703

and not showing any coverage info on the pr

**Comment by Bhuvanaarkala07** [comment]
Team,
Any update on this?

**Comment by thsaravana** [comment]
We are working on fixing some issue associated with this, but I am a bit confused on the scenario above.
1. Is this a multi module project?
2. Is the JaCoCo report available in the mentioned path?
3. If it is present, could you check the `.xml` to see if it's a valid report? We have an issue where if the `<report />` is empty, then we show `NaN` as the coverage.
You could try running the action with `debug: true` to get more information.
