### ISSUE TITLE
Support for workflow summary

### ISSUE THREAD

**Issue by yijhenlin** [Madrapps/jacoco-report#88]
Encounter `Error: HttpError: Resource not accessible by integration` if pull requests from public forked repositories.
I tried to add permissions setting in yaml and add PAT in secrets, they didn't work due to the restrictions.
[Maximum access for pull requests from public forked repositories is read-only](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
[With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow)

And output the report to workflow summary doesn't require write permission, so it will be great to have an option to support this.
Refer to: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

**Comment by thsaravana** [comment]
This is now available in [v1.7.2-alpha](https://github.com/Madrapps/jacoco-report/releases/tag/v1.7.2-alpha). We will release v1.7.2 in the coming weeks.
