### ISSUE TITLE
Wrong configuration in example

### ISSUE THREAD

**Issue by djoca** [Madrapps/jacoco-report#9]
The documentation describes `paths` as one of the required arguments, but the example has it misspelled as `path`.

![image](https://user-images.githubusercontent.com/472898/137539410-b230ff28-88d3-423e-aef8-fe7df3f3e882.png)

![image](https://user-images.githubusercontent.com/472898/137539482-cd1cf8ff-3849-4c3d-8755-61c3be3a051e.png)

**Comment by thsaravana** [comment]
Thanks @djoca . Fixed it now.
@chrsr I fixed it in `main` itself since this is tied to v1.2.
