### ISSUE TITLE
Missing security policy and dependabot workflow

### ISSUE THREAD

**Issue by w0rmr1d3r** [Madrapps/jacoco-report#90]
Hello maintainers,

I come with a couple of questions:

I see this repo lacks a security policy (see: https://github.com/Madrapps/jacoco-report/security), are there any plans to have one?

At the same time, I saw both the issue and PR about bumping/upgrading this action to use node v20, since node v16 seems to be deprecated. Are there any plans to add a .dependabot workflow to also keep up with dependencies updates?

Thank you in advance

**Comment by instrap** [comment]
Thanks for raising this issue. We have added both now.
