### ISSUE TITLE
Support workflow_run events (fix for Dependabot runs)

### ISSUE THREAD

**Issue by aaccioly** [Madrapps/jacoco-report#92]
At the moment only `pull_request`, `pull_request_target` and `push`events are supported:

https://github.com/Madrapps/jacoco-report/blob/f4a835c46ef0f03b3ecefd583f22d7c857f34925/src/action.ts#L59-L75

While `pull_request_target` used to be the way to workaround "pull requests from forked repositories" issue, `workflow_run` is much more flexible. The current modern best practice for both "Pull requests from forked repositories" and "Dependabot PRs" scenarios is to have a `pull_request`  workflow generating and uploading artifacts and a downstream `workflow_run` downloading generated artifacts and subsequently executing any privileged actions such as commenting on PRs. 

Sample actions with first class support for `workflow_run`:

* https://github.com/marketplace/actions/test-reporter
* https://github.com/marketplace/actions/publish-test-results

**Comment by thsaravana** [comment]
Interesting. Would you be able to create a PR against: https://github.com/thsaravana/jacoco-playground with this use-case so that I can test this out, and in turn use that to test the implementation as well?

**Comment by instrap** [comment]
This is in progress and will be released in `v1.7.2` . Thanks for bringing this up @aaccioly  :)

**Comment by aaccioly** [comment]
Thanks @thsaravana and @instrap. This is awesome! I somehow missed the early notification, sorry for that. I'll try to integrate the new version to a personal test project soon.

**Comment by thsaravana** [comment]
No worries :) You can use [v1.7.2-beta](https://github.com/Madrapps/jacoco-report/releases/tag/v1.7.2-beta) to test it out. We will release v1.7.2 in the coming weeks.
