### ISSUE TITLE
Uses a deprecated Node.js version

### ISSUE THREAD

**Issue by vineethvijay7** [Madrapps/jacoco-report#94]
This uses an old version :

> The following actions use a deprecated Node.js version and will be forced to run on node20: madrapps/jacoco-report@v1.6.1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by MGaetan89** [comment]
This is already fixed in `main` with https://github.com/Madrapps/jacoco-report/pull/78, and is available in the [1.7.0-alpha](https://github.com/Madrapps/jacoco-report/releases/tag/v1.7.0-alpha) version

**Comment by thsaravana** [comment]
Yes. [v1.7.0](https://github.com/Madrapps/jacoco-report/releases/tag/v1.7.0) is now publicly available.
